FROM node:12-stretch-slim AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn build

FROM alpine:3.8 AS certs

RUN apk --no-cache add ca-certificates

COPY --from=build /usr/src/app/build /build

CMD ['sh']