FROM node:12-stretch-slim AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn build

FROM nginx:stable-alpine as nginx

RUN apk --no-cache add ca-certificates

COPY --from=build /usr/src/app/build /var/www/build
COPY nginx.conf /etc/nginx/nginx.conf